apiVersion: v1
kind: Pod
metadata:
  name: test-webserver
spec:
  containers:
  - name: test-webserver
    image: registry.cloud.rennes.enst-bretagne.fr:5000/minikube_test_03
    ports:
    - containerPort: 8000
